name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */12 * * *"   # refreshes twice a day
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: VarunRaj060204
          BRANCH_NAME: "main"
          THEME: monokai
